- hosts: devstack_instance
  tasks:

  - name: Build collector directory
    shell: mkdir -p /home/ubuntu/{{ instance_name }}/logs/etc

  - name: Get stack.sh log
    fetch: src=/home/ubuntu/devstack/stack.sh.out dest={{ results_dir }}/{{ instance_name }}.stack.sh.out flat=yes validate_md5=no

  - name: Get tempest console.log
    fetch: src=/opt/stack/tempest/console.log dest={{ results_dir }}/{{ instance_name }}.console.log flat=yes validate_md5=no

  - name: Send over the collector script
    template: >
      src={{ TEMPLATE_DIR }}/ci_log_collector.j2
      dest=/home/ubuntu/ci_log_collector.sh
      mode=755

  - name: Run the collection script
    sudo: yes
    shell: bash ./ci_log_collector.sh {{ instance_name }}
    args:
      chdir: /home/ubuntu

  - name: Fetch results
    sudo: yes
    fetch: src=/home/ubuntu/{{ instance_name }}.tar.gz dest={{ results_dir }}/{{ instance_name }}.tar.gz flat=yes validate_md5=no
